#MENU菜单是否显示TAGS [布尔值...]
menu_tag: true
#MENU菜单是否显示归档 [布尔值...]
menu_arc: false

#MENU菜单显示归档后用到的参数
#归档类型=====[按年归档：yearly 按月归档：monthly]
archive_type: 'monthly'
#显示文章数====[true显示，false不显示]
show_count: true
#日期格式=====[年：YYYY或YY 月：MM]
format: 'YYYY年MM月'

#TDK网站标题说明关键字
#应用首页
title: 'hexo-blog'
subtitle: 'Every moment, are you thinking?'
keywords: '学习,博客,首页,生活,前端笔记,空间'
description: '这是一个分享我生活与前端学习的空间，欢迎访问我的博客。'
#归档
archive_title: '文章归档时间轴'
archive_keywords: '文章归档,时间轴,时间归档'
archive_description: '全部文章按照时间轴进行归档,更直观的展示,方便查看。'